version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly, day: monday }
  - package-ecosystem: maven
    directory: /backend
    schedule: { interval: weekly, day: monday }
    groups:
      spring: { patterns: ["org.springframework*"] }
      minor-and-patch: { update-types: ["minor", "patch"] }
  - package-ecosystem: npm
    directory: /frontend
    schedule: { interval: weekly, day: monday }
    groups:
      angular: { patterns: ["@angular*", "angular-eslint", "@angular-devkit*"] }
      minor-and-patch: { update-types: ["minor", "patch"] }
